server:
  ssl:
    enabled: true
    key-store: classpath:keystore/plex.p12
    key-store-type: PKCS12
    key-store-password: ssl-plex
    key-alias: plex
  error:
    include-message: always

spring:
  mysql-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/plex?createDatabaseIfNotExist=true
    username: root
    password: ENC(BaoQmlis9wnPpnwU+DrbHw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sqlite-datasource:
    jdbc-url: jdbc:sqlite:db_files/1.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

token:
  expiration: 1200

springdoc:
  api-docs:
    path: /api-docs
