spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plex?createDatabaseIfNotExist=true
    username: root
    password: ENC(4INBp3Ny/A7musp/S7w6VA==)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator